#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF
Uso:
  wp-sync-staging [--prod-wp=<id>] [--prod-db=<id>] [--staging-wp=<id>] [--staging-db=<id>] [--live-domain=<dominio>] [--staging-domain=<dominio>]
  wp-sync-staging <prod-wp-container-id> <prod-db-container-id> <staging-wp-container-id> <staging-db-container-id> <live-domain> <staging-domain>

Descripción:
  Extrae la base de datos del entorno de producción, la importa en el entorno de staging,
  y realiza un search-replace reemplazando el dominio de producción por el de staging.

Parámetros:
  --prod-wp         ID o nombre del contenedor WordPress en producción
  --prod-db         ID o nombre del contenedor DB en producción
  --staging-wp      ID o nombre del contenedor WordPress en staging
  --staging-db      ID o nombre del contenedor DB en staging
  --live-domain     Dominio del sitio en producción (con protocolo, ej: https//cuadrado.dev)
  --staging-domain  Dominio del sitio en staging (con protocolo, ej: https://staging.cuadrado.dev)

Ejemplo:
  wp-sync-staging \\
    --prod-wp=wp_prod_1 --prod-db=db_prod_1 \\
    --staging-wp=wp_staging_1 --staging-db=db_staging_1 \\
    --live-domain=https://cuadrado.dev \\
    --staging-domain=https://staging.cuadrado.dev
EOF
}

error_exit() {
  echo "❌ Error: $1" >&2
  echo
  usage
  exit 1
}

PROD_WPCLI=""
STAGING_WPCLI=""
LIVE_DOMAIN=""
STAGING_DOMAIN=""
TMP_SQL="/tmp/prod-db.sql"

PROD_WP=""
PROD_DB_HOST=""
PROD_DB_USER=""
PROD_DB_PASS=""
PROD_DB_NAME=""
PROD_DB_CONTAINER=""

STAGING_WP=""
STAGING_DB_HOST=""
STAGING_DB_USER=""
STAGING_DB_PASS=""
STAGING_DB_NAME=""
STAGING_DB_CONTAINER=""

parse_and_validate_args() {
  declare -g PROD_WP PROD_DB_CONTAINER STAGING_WP STAGING_DB_CONTAINER LIVE_DOMAIN STAGING_DOMAIN

  # Si no hay args mostrar ayuda
  if (( $# == 0 )); then
    usage
    exit 1
  fi

  # Parsing
  while (( $# > 0 )); do
    case "$1" in
      --prod-wp=*) PROD_WP="${arg#*=}" ;;
      --prod-db=*) PROD_DB_CONTAINER="${arg#*=}" ;;
      --staging-wp=*) STAGING_WP="${arg#*=}" ;;
      --staging-db=*) STAGING_DB_CONTAINER="${arg#*=}" ;;
      --live-domain=*) LIVE_DOMAIN="${arg#*=}" ;;
      --staging-domain=*) STAGING_DOMAIN="${arg#*=}" ;;
      -h|--help ) usage; exit 0 ;;
      * )
        if [[ -z "$PROD_WP" ]]; then
          PROD_WP="$1"
        elif [[ -z "$PROD_DB_CONTAINER" ]]; then
          PROD_DB_CONTAINER="$1"
        elif [[ -z "$STAGING_WP" ]]; then
          STAGING_WP="$1"
        elif [[ -z "$STAGING_DB_CONTAINER" ]]; then
          STAGING_DB_CONTAINER="$1"
        elif [[ -z "$LIVE_DOMAIN" ]]; then
          LIVE_DOMAIN="$1"
        elif [[ -z "$STAGING_DOMAIN" ]]; then
          STAGING_DOMAIN="$1"
        else
          error_exit "Argumento desconocido: $1"
        fi
        ;;
    esac
    shift || break
  done

  # Validación
  [[ -z "${PROD_WP:-}" ]] && error_exit "Falta el ID del contenedor de WordPress en producción (--prod-wp o primer parámetro)"
  [[ -z "${PROD_DB_CONTAINER:-}" ]] && error_exit "Falta el ID del contenedor de la base de datos en producción (--prod-db o segundo parámetro)"
  [[ -z "${STAGING_WP:-}" ]] && error_exit "Falta el ID del contenedor de WordPress en staging (--staging-wp o tercer parámetro)"
  [[ -z "${STAGING_DB_CONTAINER:-}" ]] && error_exit "Falta el ID del contenedor de la base de datos en staging (--staging-db o cuarto parámetro)"
  [[ -z "${LIVE_DOMAIN:-}" ]] && error_exit "Falta el dominio de producción (--live-domain o quinto parámetro)"
  [[ -z "${STAGING_DOMAIN:-}" ]] && error_exit "Falta el dominio de staging (--staging-domain o sexto parámetro)"
  echo
}


get_wp_info() {
  local id="$1"
  local env_str="$2"
  local inspect db_host db_user db_pass db_name

  inspect=$(docker inspect "$id") || error_exit "No se pudo inspeccionar el contenedor $id"

  db_user=$(echo "$inspect" | grep -o '"WORDPRESS_DB_USER=[^"]*' | cut -d= -f2)
  db_host=$(echo "$inspect" | grep -o '"WORDPRESS_DB_HOST=[^"]*' | cut -d= -f2)
  db_pass=$(echo "$inspect" | grep -o '"WORDPRESS_DB_PASSWORD=[^"]*' | cut -d= -f2)
  db_name=$(echo "$inspect" | grep -o '"WORDPRESS_DB_NAME=[^"]*' | cut -d= -f2)

  [[ -z "$db_host" || -z "$db_user" || -z "$db_pass" || -z "$db_name" ]] && error_exit "No se pudieron obtener las variables de entorno de la BD para $env_str"
  
  echo "$db_host|$db_user|$db_pass|$db_name"
}


set_variables_with_containers_data() {
  declare -g TMP_SQL PROD_DB_HOST PROD_DB_USER PROD_DB_PASS PROD_DB_NAME STAGING_HTML_PATH STAGING_DB_HOST STAGING_DB_USER STAGING_DB_PASS STAGING_DB_NAME
  
  echo "🔍 Obteniendo información de producción y staging..."
  IFS='|' read -r PROD_DB_HOST PROD_DB_USER PROD_DB_PASS PROD_DB_NAME <<<"$(get_wp_info "$PROD_WP" "producción")"
  IFS='|' read -r STAGING_DB_HOST STAGING_DB_USER STAGING_DB_PASS STAGING_DB_NAME <<<"$(get_wp_info "$STAGING_WP" "staging")"

  if [[ "$PROD_DB_HOST" != *:* ]]; then
      PROD_DB_HOST="${PROD_DB_HOST}:3306"
  fi
  if [[ "$STAGING_DB_HOST" != *:* ]]; then
      STAGING_DB_HOST="${STAGING_DB_HOST}:3306"
  fi

  TMP_SQL="/tmp/$(echo $LIVE_DOMAIN | tr -cd '[:alnum:]')_$(head -c 64 /dev/urandom | tr -dc 'a-z0-9' | fold -w 5 | head -1).sql"
}


create_wpcli_container_and_network() {
  if ! docker network ls --format '{{.Name}}' | grep -q '^wpcli$'; then
    echo "🌐 Creando red 'wpcli'..."
    docker network create wpcli >/dev/null
  fi
}


connect_containers_to_wpcli_net() {
  echo "🔗 Conectando contenedores a la red wpcli..."
  for c in "$PROD_WP" "$PROD_DB_CONTAINER" "$STAGING_WP" "$STAGING_DB_CONTAINER"; do
    docker network connect wpcli "$c" 2>/dev/null || true
  done

  echo "📡 Comprobando visibilidad de las bases de datos en la red temporal..."
  DB_HOST_NC=$(echo "$PROD_DB_HOST" | cut -d: -f1)
  DB_PORT_NC=$(echo "$PROD_DB_HOST" | cut -d: -f2)

  TEMP_CONTAINER=$(docker run -d --rm --network wpcli wordpress:cli tail -f /dev/null)

  if ! docker exec $TEMP_CONTAINER /bin/bash -c "nc -vz $DB_HOST_NC $DB_PORT_NC" >/dev/null 2>&1; then
    echo "⚠️  Haciendo fallback para el host de la BD de producción..."
    DB_INSPECT=$(docker inspect "$PROD_DB_CONTAINER") || error_exit "No se pudo inspeccionar el contenedor de la BD de producción"
    DB_CONTAINER_NAME=$(echo "$DB_INSPECT" | grep '"Name":' | head -1 | cut -d: -f2 | tr -d '", ' | sed 's/^\///')
    [[ -z "$DB_CONTAINER_NAME" ]] && error_exit "No se pudo obtener el nombre del contenedor de la BD de producción para el fallback."
    
    PROD_DB_HOST="${DB_CONTAINER_NAME}:${DB_PORT_NC}"
    echo "♻️  Usando fallback con nombre del contenedor: $PROD_DB_HOST"
  else
    echo "✅ La BD de producción es visible."
  fi

  DB_HOST_NC=$(echo "$STAGING_DB_HOST" | cut -d: -f1)
  DB_PORT_NC=$(echo "$STAGING_DB_HOST" | cut -d: -f2)

  if ! docker exec $TEMP_CONTAINER /bin/bash -c "nc -vz $DB_HOST_NC $DB_PORT_NC" >/dev/null 2>&1; then
    echo "⚠️  Haciendo fallback para el host de la BD de staging..."
    DB_INSPECT=$(docker inspect "$STAGING_DB_CONTAINER") || error_exit "No se pudo inspeccionar el contenedor de la BD de staging"
    DB_CONTAINER_NAME=$(echo "$DB_INSPECT" | grep '"Name":' | head -1 | cut -d: -f2 | tr -d '", ' | sed 's/^\///')
    [[ -z "$DB_CONTAINER_NAME" ]] && error_exit "No se pudo obtener el nombre del contenedor de la BD de staging para el fallback."
    
    STAGING_DB_HOST="${DB_CONTAINER_NAME}:${DB_PORT_NC}"
    echo "♻️  Usando fallback con nombre del contenedor: $STAGING_DB_HOST"
  else
    echo "✅ La BD de staging es visible."
  fi
  
  docker rm -f $TEMP_CONTAINER >/dev/null 2>&1 || true
}


sync_databases() {
  declare -g PROD_WPCLI STAGING_WPCLI
  echo "🚀 Levantando contenedores temporales..."
  PROD_WPCLI=$(docker run -d --rm -it \
    --volumes-from "$PROD_WP" \
    --network wpcli \
    -e WORDPRESS_DB_HOST="${PROD_DB_HOST}" \
    -e WORDPRESS_DB_USER="${PROD_DB_USER}" \
    -e WORDPRESS_DB_PASSWORD="${PROD_DB_PASS}" \
    -e WORDPRESS_DB_NAME="${PROD_DB_NAME}" \
    wordpress:cli tail -f /dev/null)

  STAGING_WPCLI=$(docker run -d --rm \
    --volumes-from "$STAGING_WP" \
    --network wpcli \
    -e WORDPRESS_DB_HOST="${STAGING_DB_HOST}" \
    -e WORDPRESS_DB_USER="${STAGING_DB_USER}" \
    -e WORDPRESS_DB_PASSWORD="${STAGING_DB_PASS}" \
    -e WORDPRESS_DB_NAME="${STAGING_DB_NAME}" \
    wordpress:cli tail -f /dev/null)
  
  # WP-CLI usa mariadb, si se intenta importar o exportar una bd mysql falla. Estas lineas comprueban 
  # si las bd son mysql; si lo son, instala el paquete mariadb-connector-c para corregir el error.
  docker inspect --format='{{.Config.Image}}' "$PROD_DB_CONTAINER" | grep -iq "mysql" && docker exec --user root "$PROD_WPCLI" sh -c "apk update && apk add mariadb-connector-c --no-cache" >/dev/null
  docker inspect --format='{{.Config.Image}}' "$STAGING_DB_CONTAINER" | grep -iq "mysql" && docker exec --user root "$STAGING_WPCLI" sh -c "apk update && apk add mariadb-connector-c --no-cache" >/dev/null
  
  echo "⬇️ Exportando base de datos desde producción..."
  docker exec $PROD_WPCLI wp db export $TMP_SQL --path=/var/www/html --allow-root >/dev/null

  echo "⬆️ Importando base de datos a staging..."
  docker cp $PROD_WPCLI:$TMP_SQL $TMP_SQL >/dev/null && docker cp $TMP_SQL $STAGING_WPCLI:$TMP_SQL >/dev/null
  docker exec $STAGING_WPCLI wp db import $TMP_SQL --path=/var/www/html --allow-root >/dev/null

  echo "🔍 Reemplazando '$LIVE_DOMAIN' por '$STAGING_DOMAIN'..."
  REPLACE_COUNT=$(docker exec $STAGING_WPCLI wp search-replace "$LIVE_DOMAIN" "$STAGING_DOMAIN" --format=count --path=/var/www/html)

  echo "🔁 Reemplazados $REPLACE_COUNT registros de '$LIVE_DOMAIN' por '$STAGING_DOMAIN'."
  echo "✅ Sincronización completada correctamente."
}


cleanup() {
  rm -f $TMP_SQL >/dev/null 2>&1 || true    
  docker rm -f $STAGING_WPCLI >/dev/null 2>&1 || true
  docker rm -f $PROD_WPCLI >/dev/null 2>&1 || true
  for c in "$PROD_WP" "$PROD_DB_CONTAINER" "$STAGING_WP" "$STAGING_DB_CONTAINER"; do
    docker network disconnect wpcli "$c" 2>/dev/null || true
  done
}
trap cleanup EXIT


main() {
  parse_and_validate_args "$@"
  set_variables_with_containers_data
  # create_wpcli_container_and_network
  # connect_containers_to_wpcli_net
  # sync_databases
  # cleanup
}

main "$@"